name: bdui_server

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  http: ^1.6.0
  get_it: ^7.6.4
  shared:
    path: ../shared

dev_dependencies:
  test: ^1.21.0
